address: 0.0.0.0
port: 80
auth: true
tls: false
prefix: /

users:
  - username: admin_username
    password: your_secure_password
    directory: /data
    modify: true
    rules: []

  - username: reader
    password: guest_password
    directory: /data
    modify: false  
    rules: []