services:
  webdav:
    image: hacdias/webdav:v5
    container_name: gringotts-vault
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/webdav/config.yaml
      # mounting to external digital ocean volume
      - /mnt/vol_azkaban_1/notes:/data
    ports:
      - "0.0.0.0:9876:80"
    command: -c /etc/webdav/config.yaml
  filestash:
    image: machines/filestash:latest
    container_name: gringotts-goblin
    restart: unless-stopped
    ports:
      - "8334:8334"
    # This dummy volume just saves your login session/settings, not the files.
    volumes:
      - filestash_data:/app/data/state/

volumes:
  filestash_data: